# Generated by Django 5.0.7 on 2024-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastUpdated',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
